version: '3.9'
services:
  frontend:
    build: ./front-end
    volumes: 
      - ./front-end/src:/front-end/src
    ports:
      - 3000:3000
    platform: linux/x86_64
    working_dir: /front-end
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5
  backend:
    container_name: app_backend
    build: ./back-end
    ports:
      - 3001:3001
    platform: linux/x86_64
    working_dir: /back-end
    command: dev 
    volumes: 
      - ./back-end/src:/back-end/src
    depends_on:
      db:
        condition: service_healthy
    environment:
      - API_PORT=3001
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=senhaDoDB
      - MYSQL_DB_NAME=delivery-app
      - EVAL_ALWAYS_RESTORE_DEV_DB=true
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
  db:
    image: mysql:8.0.21
    container_name: db
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      - NODE_ENV=development
      - MYSQL_ROOT_PASSWORD=senhaDoDB
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE